### ISSUE TITLE
Aarch64 support?

### ISSUE THREAD

**Issue by ilg-ul** [stm32duino/arm-none-eabi-gcc#3]
Are there any plans to upgrade stm32duino to run on Aarch64?

If the only limitation is a toolchain, please note that I'm considering adding Aarch support to the xPack binaries, but no date when this will be available is set yet.

**Comment by fpistm** [comment]
Hi @ilg-ul 
This is something requested by the community:
https://github.com/stm32duino/Arduino_Core_STM32/issues/708

And yes the main (only) limitation is the toolchain. So if you add it this would be great.
Arduino IDE support those 2 targets:
 - aarch64-linux-gnu
- arm-linux-gnueabihf

**Comment by ilg-ul** [comment]
Yes, I'll try to add it, but currently finding an environment to build these images is not easy.

I'll probably have to buy a Pi 4, although performances are modest for such an intensive task as building toolchains.

For the moment, for Aarch64, you can repack the recently released Arm binary: 

https://developer.arm.com/tools-and-software/open-source-software/developer-tools/gnu-toolchain/gnu-rm/downloads

**Comment by ilg-ul** [comment]
I did a quick review, and it looks like some of my assumptions were too optimistic.

At this moment, even if the hardware supports 64-bit since Pi 3, the Arm mini-pc world is mainly 32-bit, with Raspbian still a 32-bit OS.

There are some 3rd party projects adding 64-bit support to existing Linux distros, but I would not go that route.

There are other small boards that come with initial support for Debian Arm 64-bit (like https://www.pine64.org/rockpro64/).

I'll further investigate, and probably order one such board, but I don't expect this to happen before the end of this year.

Anyway, what also results from this quick analysis is that both aarch64 and armhf should be considered.

**Comment by fpistm** [comment]
Don't worry
Again thanks a lot for your great work 🥇

**Comment by ilg-ul** [comment]
You're welcome!

The 9.x toolchain is ready, I have to test it, it'll probably be public in 1-2 days.

**Comment by fpistm** [comment]
@ilg-ul 
I close this one as it will be handled here:
https://github.com/stm32duino/Arduino_Core_STM32/issues/708

Moreover, I will probably archive this repo.

**Comment by ilg-ul** [comment]
Ok, no problem.
